---
title: "MIXFISH ShinyApp data explorer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About the data explorer

This data explorer structure is intended to allow examination of the data used in Mixed fishery forecasts using FCube. You can explore both the "raw" accessions data and the processed FLFleet objects.

There are a number of different apps available, as detailed below.

At the begining of each script/app there is a variable 'Area', which needs to be changed by the user (e.g. North_Sea, Celtic_Sea etc...)

The app has been tested to work for the North Sea and Celtic Sea.

## Data preparation

**1.data_prep** must be run first to produce the input data files for the apps. This includes two scripts;

*Accessions_PreProcessing.R* : This takes all the accessions files as inputs and produced a consistent effort file across all areas and countries (/Combined_accession_data/Accessions_Effort.RData) and similarly a landings file (/Combined_accession_data/Accessions_Catch.RData)

*FLFLeet_data_extraction.R* : This works on the FLFleet objects for each area (you can set the area in the script) and produces the processed inputs to the apps.

## Available apps

At the moment, the following is available (to run the app, go into the folder and open/run **app.R**):

**2.Raw accession app** : The accession data as submitted by each country. Tabs include:

* Accession catch table - landings and discards as submitted
* Accession effort table - effort as submitted
* Catch plots - bar plots of catch data by country, year, metier area, species (these can be downloaded)
* Effort plots - line plots of effort data by country, year, metier, area (these can be downloaded)
* LPUE plots - landings per unit effort line plots by country, year, metier, area and species
* Value plots - bar plots of value data by country, year, metier area, species (these can be downloaded)

**3.Effort app** : The effort following aggregation for use in FCube. Tabs include:

* Fleet effort table - effort and effort share by year, country, fleet, metier
* Effort time series - effort time series plots by country, fleet and metier
  
**4.catchability app** : log(catchability) estimates by year, stock, country, fleet, metier

* Fleet catchability tables - tables which can be filtered by year and stock
* Catchability plots - plots of log(catchability) estimates, including a estimated linear fit. Can be filtered by country and stock.

**5.partial F app** : The estimated partial fishing mortalities.

* Fleet partial F tables - tables which can be filtered by year and stock detailing partial fishing mortality estimates by year, stock, country, fleet and metier.
* Partial F time series - plots of partial F by country, stock, fleet and metier
* Partial F spider chart - plots of proportion of fishing mortality contributed by each fleet to each stock.

**6.quota share app** : The estimated landings share per fleet

* Fleet landings share tables - the landings, proportion of the stock to total fleet landings (i.e. catch composition), and stock landings share (i.e. quota share) for each fleet, stock and year.
* Landings share time series - proportion of landings for each stock by each fleet as a time series plot.
* Landings composition time series - bar plots with the contribution of the landings of each stock to the total fleets landings (total landings in weight given in numbers)

## Development notes

* We should probably move plotting over to ggplot2 with plotly at some point, which will allow more interactive data exploration.

Edited:  Paul Dolder - 20/10/2017
Updated: Paul Dolder - 21/05/2018